export interface CidItem {
  code: string;
  name: string;
}

export const CID_LIST: CidItem[] = [
  { code: 'A09', name: 'Diarreia e gastroenterite de origem infecciosa presumida' },
  { code: 'B34', name: 'Doenças por vírus, de localização não especificada' },
  { code: 'C50', name: 'Neoplasia maligna da mama' },
  { code: 'D64', name: 'Outras anemias' },
  { code: 'E10', name: 'Diabetes mellitus insulinodependente' },
  { code: 'E11', name: 'Diabetes mellitus não-insulinodependente' },
  { code: 'E14', name: 'Diabetes mellitus não especificado' },
  { code: 'E66', name: 'Obesidade' },
  { code: 'E78', name: 'Distúrbios do metabolismo de lipoproteínas e outras lipidemias' },
  { code: 'F32', name: 'Episódios depressivos' },
  { code: 'F33', name: 'Transtorno depressivo recorrente' },
  { code: 'F41', name: 'Outros transtornos ansiosos (Ansiedade generalizada)' },
  { code: 'F43', name: 'Reações ao estresse grave e transtornos de adaptação' },
  { code: 'G40', name: 'Epilepsia' },
  { code: 'G43', name: 'Enxaqueca' },
  { code: 'G44', name: 'Outras síndromes de cefaleia' },
  { code: 'G47', name: 'Distúrbios do sono (Insônia)' },
  { code: 'H10', name: 'Conjuntivite' },
  { code: 'H52', name: 'Transtornos de refração e da acomodação' },
  { code: 'I10', name: 'Hipertensão essencial (primária)' },
  { code: 'I11', name: 'Doença cardíaca hipertensiva' },
  { code: 'I20', name: 'Angina pectoris' },
  { code: 'I25', name: 'Doença isquêmica crônica do coração' },
  { code: 'I50', name: 'Insuficiência cardíaca' },
  { code: 'J00', name: 'Nasofaringite aguda (resfriado comum)' },
  { code: 'J01', name: 'Sinusite aguda' },
  { code: 'J02', name: 'Faringite aguda' },
  { code: 'J03', name: 'Amigdalite aguda' },
  { code: 'J04', name: 'Laringite e traqueíte agudas' },
  { code: 'J06', name: 'Infecções agudas das vias aéreas superiores de localização múltipla' },
  { code: 'J20', name: 'Bronquite aguda' },
  { code: 'J30', name: 'Rinite alérgica e vasomotora' },
  { code: 'J32', name: 'Sinusite crônica' },
  { code: 'J40', name: 'Bronquite não especificada como aguda ou crônica' },
  { code: 'J44', name: 'Outras doenças pulmonares obstrutivas crônicas (DPOC)' },
  { code: 'J45', name: 'Asma' },
  { code: 'K20', name: 'Esofagite' },
  { code: 'K21', name: 'Doença de refluxo gastroesofágico' },
  { code: 'K25', name: 'Úlcera gástrica' },
  { code: 'K29', name: 'Gastrite e duodenite' },
  { code: 'K30', name: 'Dispepsia' },
  { code: 'K58', name: 'Síndrome do cólon irritável' },
  { code: 'K59', name: 'Outros transtornos funcionais do intestino (Constipação)' },
  { code: 'L20', name: 'Dermatite atópica' },
  { code: 'L23', name: 'Dermatites alérgicas de contato' },
  { code: 'L50', name: 'Urticária' },
  { code: 'M15', name: 'Poliartrose' },
  { code: 'M16', name: 'Coxartrose (artrose do quadril)' },
  { code: 'M17', name: 'Gonartrose (artrose do joelho)' },
  { code: 'M25', name: 'Outros transtornos articulares não classificados (Dor articular)' },
  { code: 'M47', name: 'Espondilose' },
  { code: 'M54', name: 'Dorsalgia (Dor nas costas, cervicalgia, lombalgia)' },
  { code: 'M75', name: 'Lesões do ombro (Tendinite/capsulite)' },
  { code: 'M77', name: 'Outras entesopatias (Epicondilite)' },
  { code: 'M79', name: 'Outros transtornos dos tecidos moles (Dor em membros/fibromialgia)' },
  { code: 'N30', name: 'Cistite' },
  { code: 'N39', name: 'Outros transtornos do aparelho urinário (Infecção urinária)' },
  { code: 'N97', name: 'Infertilidade feminina' },
  { code: 'O14', name: 'Hipertensão gestacional com proteinúria significativa (Pré-eclâmpsia)' },
  { code: 'O21', name: 'Vômitos excessivos na gravidez' },
  { code: 'O80', name: 'Parto único espontâneo (Parto normal)' },
  { code: 'R05', name: 'Tosse' },
  { code: 'R07', name: 'Dor na garganta e no peito' },
  { code: 'R10', name: 'Dor abdominal e pélvica' },
  { code: 'R11', name: 'Náusea e vômito' },
  { code: 'R30', name: 'Dor associada à micção (Disúria)' },
  { code: 'R42', name: 'Tontura e instabilidade' },
  { code: 'R50', name: 'Febre de origem desconhecida' },
  { code: 'R51', name: 'Cefaleia (Dor de cabeça)' },
  { code: 'R52', name: 'Dor não classificada em outra parte' },
  { code: 'R53', name: 'Mal-estar e fadiga' },
  { code: 'S09', name: 'Outros traumatismos da cabeça' },
  { code: 'S39', name: 'Outros traumatismos do abdômen, do dorso e da pelve' },
  { code: 'S63', name: 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do punho' },
  { code: 'S93', name: 'Luxação, entorse e distensão das articulações e dos ligamentos ao nível do tornozelo' },
  { code: 'T14', name: 'Traumatismo de região não especificada do corpo' },
  { code: 'Z00', name: 'Exame geral e investigação de pessoas sem queixas ou diagnóstico' },
  { code: 'Z01', name: 'Outros exames especiais e investigações de pessoas sem queixas' },
  { code: 'Z02', name: 'Exame para fins administrativos (Admissional/demissional)' },
  { code: 'Z39', name: 'Cuidados e exames pós-parto' }
];
