export const EXAM_LIST: string[] = [
  'Amniocentese',
  'Arteriografia (angiografia)',
  'Audiometria',
  'Auscultação',
  'Estudos com radiografia de bário',
  'Biópsia',
  'Medição de pressão arterial',
  'Exames de sangue',
  'Aspiração da medula óssea',
  'Broncoscopia',
  'Cateterismo cardíaco',
  'Amostras de vilosidades coriônicas',
  'Análise cromossômica',
  'Colonoscopia',
  'Colposcopia',
  'Tomografia computadorizada (TC)',
  'Biópsia de cone',
  'Cultura',
  'Dilatação e curetagem (D e C)',
  'Absorciometria de raios-X dupla (DEXA)',
  'Ecocardiograma',
  'Eletrocardiograma (ECG)',
  'Eletroencefalograma (EEG)',
  'Eletromiografia',
  'Teste eletrofisiológico',
  'Colangiopancreatografia retrógrada endoscópica (CPRE)',
  'Endoscopia',
  'Teste imunoabsorvente ligado à enzima (ELISA)',
  'Fluoroscopia',
  'Histeroscopia',
  'Urografia intravenosa',
  'Aspiração da articulação',
  'Laparoscopia',
  'Ressonância magnética (RM)',
  'Mamografia',
  'Mediastinoscopia',
  'Mielografia',
  'Estudo da condução nervosa',
  'Exames para detectar sangue oculto',
  'Oftalmoscopia',
  'Exame de Papanicolau',
  'Paracentese',
  'Colangiografia percutânea trans-hepática',
  'Tomografia por emissão de pósitrons (TEP)',
  'Testes de função pulmonar',
  'Cintilografia',
  'Exames para testar os reflexos',
  'Punção lombar',
  'Exame de urina (urinálise)'
];
